version: '3'
services:
  validator_service:
    image: infernocommunity/fhir-validator-service
    # Update this path to match your directory structure
    volumes:
      - ./lib/us_core_test_kit/igs:/home/igs
  fhir_validator_app:
    image: infernocommunity/fhir-validator-app
    depends_on:
      - validator_service
    environment:
      EXTERNAL_VALIDATOR_URL: http://localhost/validatorapi
      VALIDATOR_BASE_PATH: /validator
  nginx:
    image: nginx
    volumes:
      - ./config/nginx.background.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    command: [nginx, '-g', 'daemon off;']
    depends_on:
      - fhir_validator_app
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
